### ISSUE TITLE
Update for New Keenetic UI Compatibility

### ISSUE THREAD

**Issue by keyiflerolsun** [Eralde/keenetic-dark-theme-extension#6]
Hi,

First of all, thank you for creating this extension. I really enjoy using it with my Keenetic router.

Recently, Keenetic updated their interface, and it seems like this extension is not fully compatible with the new UI. Are there any plans to update the extension to work with the latest Keenetic UI?

**Comment by Eralde** [comment]
Hi @keyiflerolsun :)

Thank you for your kind words, but unfortunately I don't think I will continue to develop this extension.

The new version of the web UI completely replaced the older one in the latest Keenetic firmware. The new UI has a dark theme already built in. Also it is built with a different framework (Angular instead of AngularJS), so any patches or workarounds in runtime are almost impossible to implement. So most of "extra functions" added by my extensions will be lost. That being said, my extension kind of lost it's purpose.

If you want to discuss adding some parts of this extension to the UI, I would suggest that you start a thread on the Keenetic forum: https://forum.keenetic.com

**Comment by keyiflerolsun** [comment]
Especially the ease of adding Static Routes, exporting and importing was very useful to me.

Thank you for your help so far and have a nice day.

**Comment by keyiflerolsun** [comment]
I wrote an easy python tool to add Static Routes inspired by your code :)

https://github.com/keyiflerolsun/KeeneticPy?tab=readme-ov-file#domain-veya-asn-ile-rota-ekleme

**Comment by Eralde** [comment]
> I wrote an easy python tool to add Static Routes inspired by your code :)
> 
> https://github.com/keyiflerolsun/KeeneticPy?tab=readme-ov-file#domain-veya-asn-ile-rota-ekleme

Looks cool 🚀 
If you have any questions on how to use the **rci/** API, feel free to ask :)
